language: cpp
dist: trusty

env:
  global:
   - secure: "kzCmAIYygxPZIEL0vJ0ntJAPiN5Oc6R1hg5F5z6gLVz4GrbQSOJW2evul9NF82wwLeNs5KoM7fOKKGLB2XitVh5iVE8RMDp4a/4aQkT7bVUUV7q1rJYsnFZ3RN3MiVeMlRX/XswIlgdPbq9MOADdgO6+SVcdxo217tujtBly3SIJhINrnUxMBAU0ZbtX3z4sC1xjH6zTp4LTjfOwpGCvsyoihCb8yAzP/bGYnymN83KTRCBdXustwDRmfukxX8gUP4G3kwWk5ygy9iH2b/svyOTn5L1Q5J1O+3uOaSVGKLKBbtxj6IzNyXkr8LJxAhqyLVWDQkP6QI0zztXvE+9dgrBaPksToAosP2ClyLty0q+h4fOBxgkOqtfq096X4Zerwh1W38nyVzdOn7LFwsU57KkXRdiSYiWYos+AcQIsXa+dJUAspIcQPAPo2OIEsPWEy/Ey1oO5AGgcoRgmSRWPLNfxDwXQAGtZPnqHTnUgzhKkBz6L1oNs7bRLhAPMFz2g0WZJTxOcM3EmsxEEBQKKLiEsa+pSicHPmhSq+Sa5tK/MZzExsqLnBrUgmXwAmG7YAJcWmjpowJodI+6qOhr+g/K5rLDilDFehCABDfeSaJBNtpaLPOH8neFop7Tci3WZBfWjzcC2nIaCj/FtLrmXOnIah0G27TYQUvF813t967E="

matrix:
  include:
  - env: GCC_VERSION=5
    os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-5

before_install:
- if [ -n "$GCC_VERSION" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}";
  fi
- if [ -n "$CLANG_VERSION" ]; then export CXX="clang++-${CLANG_VERSION}" CC="clang-${CLANG_VERSION}";
  fi
- which $CXX
- which $CC
- "$CXX --version"

script:
- cmake -DCMAKE_CXX_FLAGS=-Werror .
- make
- "./unit_tests"

addons:
  coverity_scan:
    project:
      name: "vladimirgamalyan/fontbm"
      description: "Build submitted via Travis CI"
    notification_email: vladimir.gamalian@gmail.com
    build_command_prepend: "cmake ."
    build_command:   "make"
    branch_pattern: coverity_scan

deploy:
  provider: releases
  api_key:
    secure: d6b/6Z50XUCe6Ucjyb8Cglcb9mS2eTUVUkT24nsK1zVoZcPOFN5fCzPMTnJ+QPl1w3YypoYQR4r/kD1POA4ozaul9qjGK0T3zDYAlmr7jS9+f5ehRrY8Vtl2ii4CiDYgQ3/KAHgiHcGBQPosV7+AEMkzVLj0AQ6QjIfQuMIlf19l/i4c5cn/Z4lVp3AnjaFVFNYVB5ZdP8lqf5GIZf1YgflkuvpeSDjlkzXfajwFh8ZiQUDm5VtEr4tySbFyDQjnW8r2sff1MvVZCdEDs2N5CS5Hqikrry4kneOI46NdGwr1RDRXzAibZa6E9V3ACgYAZEAlvGKpM+YKD91/u4ATnTIhowlKqWDwN3cfXLZ0haXd02lJI8B4Vt5Ls3hrc/IlrbEF8TwuDO6jgtMqgva4K/rXQkgK7dIrNkC214TpxOjXDwLIQdJCig/czr7orunjOOtL+WPjRgLeYSP2e0/3SUd2imWvJ2T9FRB5looj8QXi/RmUg3UZJi37mZue6/xfvzv0URbd0ZUxRQFnrVZa6v0tAYhaiQ3jBFZPUKLEMshRD1hj6c2qb+7gWa8AwL3caeJlpZk0kwpdtVH4UWVVFHQJe8tu4pam6bm/deRNrhScp4x2lpHiJ0H4MkQZVsxi/lc/RgYmS5I+Ok1QTCQTNaOiEtXFKNXD5wpgWu4dc+A=
  file: "./fontbm"
  skip_cleanup: true
#  overwrite: true
  on:
    branch: release
    tags: true

notifications:
  email: false
