language: cpp
sudo: required
dist: trusty

matrix:
  include:
    - env: GCC_VERSION=5
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
#    - env: CLANG_VERSION=3.9
#      os: linux
#      addons:
#        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#            - llvm-toolchain-precise
#          packages:
#            - clang-3.9

before_install:
#  - sudo apt-get update -qq
#  - sudo apt-get install -qq libfreetype6-dev
  - if [ -n "$GCC_VERSION" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi
  - if [ -n "$CLANG_VERSION" ]; then export CXX="clang++-${CLANG_VERSION}" CC="clang-${CLANG_VERSION}"; fi  
  - which $CXX
  - which $CC
  - $CXX --version
  
script:
  - cmake -DCMAKE_CXX_FLAGS=-Werror .
  - make
  - ./src/tests/tests
  - cd tests
  - python functional_tests.py ../src/fontbm

notifications:
  email: false
