os:
  - Visual Studio 2015

configuration:
  - Release

platform:
  - Win32
  
install:
  - vcpkg install freetype
  
cache:
  - c:\tools\vcpkg\installed\  

before_build:
  - cmake -G "Visual Studio 14 2015" -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake
#  - set PATH=c:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%

build:
  project: fontbm.sln
