os:
  - Visual Studio 2015

configuration:
  - Release

platform:
  - Win32
  
install:
  - vcpkg install freetype
  
cache:
  - c:\tools\vcpkg\installed\  

before_build:
  - cmake -G "Visual Studio 14 2015" -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake

build:
  project: fontbm.sln
  
after_build:
 - 7z a fontbm.zip "src/Release/*"

artifacts:
  - path: fontbm.zip
    name: fontbm
